### ISSUE TITLE
ethon:loggedBy

### ISSUE THREAD

**Issue by jo-tud** [ConsenSys/EthOn#117]
The actual meaning of `ethon:loggedBy` is not well described yet.

I understand it as: "Relates a logEntry to the ContractAccount that the LogEntry was created in.". The description should be improved accordingly.

We also have: `hasLogEntry` which relates the Tx that includes the log somewhere in its call tree to the log Entry.
What is still missing is a relation that connects the LogEntry with the actual Msg that called the contract and resulted in the Log. This may be Account that created the Tx or a Contract somewhere down the call tree.

**Comment by webthethird** [comment]
@jo-tud Sorry this slipped my mind until now. So are you proposing that we create a new object property, say `ethon:logOrigin`, with a domain `Log Entry` and range `Message`? Or would the range be the `Account`, which could be an External Account or a Contract Account, that sent the original message?

**Comment by jo-tud** [comment]
fixed https://github.com/ConsenSys/EthOn/commit/145212a892a6b3453ff2c9c9e99f02ae96bdbf8f
