### ISSUE TITLE
callTx/createTx error state

### ISSUE THREAD

**Issue by cubedro** [ConsenSys/EthOn#17]
Should there be some way of displaying if a callTx/createTx/suicideTx failed during execution eg: Out of gas, Bad destination jump etc.?

**Comment by jo-tud** [comment]
Yes, I think that would be a useful extension. Is there an existing resource that helps classifying the different error types? A list of possible errors that may occur during block and transaction validation?
What errors are recorded to the blockchain?

**Comment by jo-tud** [comment]
I just added the string given by the parity client for the moment being
