### ISSUE TITLE
Clarify relation between msgGasUsed and txGasUsed

### ISSUE THREAD

**Issue by jo-tud** [ConsenSys/EthOn#77]
My current view ist that `txGasUsed` should be cumulative for all Messages resulting from a Tx and `msgGasUsed` should be the gas used for exactly one Message, be it a Tx or a CM.
Currently the definition does not reflect that.
@infsaulo

**Comment by jo-tud** [comment]
Also, currently Tx don't have a msgGasUsed at all

**Comment by jo-tud** [comment]
@webthethird Can you take care of this, please?

**Comment by webthethird** [comment]
@chronaeon you and I should probably tackle this together, as it's a definition clarification

**Comment by jo-tud** [comment]
We still have a problem here. The Domain of `msgGasUsed` should be `ethon:Msg` not `ethon:ContractMsg`. @webthethird Can you create a PR for that?

**Comment by jo-tud** [comment]
closed via #126
